export const CATEGORIES = ['All', 'Development', 'Design', 'Business', 'AI & Future', 'Education', 'Technology', 'Marketing', 'Productivity', 'AI Tools', 'Prompts'];

export const GENERATED_PROMPTS = Array.from({ length: 100 }, (_, i) => ({
  id: 1000 + i,
  type: 'prompt',
  title: `AI Prompt #${i + 1}: ${['Creative Writing', 'Code Optimization', 'Marketing Copy', 'Data Analysis', 'Language Translation', 'Legal Research'][i % 6]}`,
  author: ['AI Expert', 'Prompt Engineer', 'SkillBloomer AI', 'Tech Guru'][i % 4],
  authorAvatar: 'AI',
  authorRole: 'AI Specialist',
  thumbnail: `https://picsum.photos/seed/prompt${i}/800/450`,
  category: 'Prompts',
  publishedAt: `${(i % 10) + 1} days ago`,
  isBusiness: i % 5 === 0,
  content: `This is a highly optimized prompt for ${['generating high-quality code', 'writing engaging blog posts', 'analyzing complex datasets', 'creating stunning visual art descriptions'][i % 4]}. Use this to get the best results from LLMs.`,
  tags: ['AI', 'Productivity', 'Efficiency']
}));

export const GENERATED_AI_TOOLS = Array.from({ length: 20 }, (_, i) => ({
  id: 2000 + i,
  type: 'ai-tool',
  title: `AI Tool #${i + 1}: ${['NeuralWriter', 'CodeAssistant', 'VisionGen', 'DataBot', 'VoiceSync', 'MarketAI'][i % 6]}`,
  author: ['AI Labs', 'FutureTech', 'OpenSource AI', 'SkillBloomer'][i % 4],
  authorAvatar: 'AT',
  authorRole: 'Tool Developer',
  thumbnail: `https://picsum.photos/seed/aitool${i}/800/450`,
  category: 'AI Tools',
  publishedAt: `${(i % 5) + 1} weeks ago`,
  isBusiness: true,
  url: '#',
  description: `A state-of-the-art AI tool designed for ${['automated content creation', 'intelligent code refactoring', 'real-time data visualization', 'advanced sentiment analysis'][i % 4]}.`,
  rating: 4.5 + (i % 5) * 0.1
}));

export const GENERATED_COLLEGES = Array.from({ length: 15 }, (_, i) => ({
  id: 3000 + i,
  type: 'college',
  title: `${['MIT', 'Oxford', 'Cambridge', 'INSEAD', 'Wharton', 'Kellogg'][i % 6]} ${['School of Management', 'Institute of Tech', 'Business School'][i % 3]}`,
  author: 'University Admin',
  authorAvatar: 'UA',
  authorRole: 'Educational Institution',
  thumbnail: `https://picsum.photos/seed/college${i}/800/450`,
  location: ['Boston, MA', 'Oxford, UK', 'Cambridge, UK', 'Fontainebleau, FR', 'Philadelphia, PA', 'Evanston, IL'][i % 6],
  programs: 5 + (i % 10),
  category: 'Education',
  publishedAt: `${(i % 7) + 1} days ago`,
  isBusiness: true
}));

export const GENERATED_JOBS = Array.from({ length: 20 }, (_, i) => ({
  id: 4000 + i,
  type: 'job',
  title: [
    'Frontend Developer (React)',
    'UI/UX Designer',
    'Product Manager',
    'Data Scientist',
    'Backend Engineer (Node.js)',
    'Marketing Specialist',
    'Business Analyst',
    'Mobile App Developer (Flutter)',
    'DevOps Engineer',
    'Content Strategist'
  ][i % 10],
  company: ['Google', 'Meta', 'Amazon', 'Netflix', 'Apple', 'Microsoft', 'Adobe', 'Spotify', 'Airbnb', 'Uber'][i % 10],
  location: ['Remote', 'San Francisco, CA', 'New York, NY', 'London, UK', 'Berlin, Germany', 'Bangalore, India', 'Singapore', 'Austin, TX', 'Seattle, WA', 'Toronto, Canada'][i % 10],
  salary: ['$80k - $120k', '$70k - $110k', '$90k - $140k', '$100k - $160k', '$85k - $130k', '$60k - $90k', '$75k - $115k', '$80k - $125k', '$95k - $150k', '$55k - $85k'][i % 10],
  thumbnail: `https://picsum.photos/seed/job${i}/400/400`,
  category: ['Development', 'Design', 'Business', 'Marketing'][i % 4],
  type_job: ['Full-time', 'Part-time', 'Contract', 'Internship'][i % 4],
  description: 'Join our world-class team to build the future of technology and design.',
  author: ['Google', 'Meta', 'Amazon', 'Netflix', 'Apple', 'Microsoft', 'Adobe', 'Spotify', 'Airbnb', 'Uber'][i % 10],
  authorAvatar: ['G', 'M', 'A', 'N', 'A', 'M', 'A', 'S', 'A', 'U'][i % 10],
  authorRole: 'Hiring Team',
  publishedAt: `${(i % 5) + 1} days ago`,
  isBusiness: true
}));

export const PUBLISHED_CONTENT = [
  ...GENERATED_PROMPTS,
  ...GENERATED_AI_TOOLS,
  ...GENERATED_COLLEGES,
  ...GENERATED_JOBS,
  {
    id: 1,
    type: 'course',
    title: 'Mastering React & Next.js 14',
    author: 'Ankur Awasthi',
    authorAvatar: 'AA',
    authorRole: 'Full-stack Instructor',
    thumbnail: 'https://picsum.photos/seed/react/800/450',
    duration: '12h 45m',
    rating: 4.9,
    students: 1240,
    price: '$49.99',
    category: 'Development',
    publishedAt: '2 days ago',
    isBusiness: false
  },
  {
    id: 2,
    type: 'article',
    title: 'The Future of AI in Education',
    author: 'SkillBloomer Business',
    authorAvatar: 'SB',
    authorRole: 'Educational Platform',
    thumbnail: 'https://picsum.photos/seed/ai/800/450',
    readTime: '8 min read',
    likes: 856,
    comments: 42,
    category: 'AI & Future',
    publishedAt: '5 hours ago',
    isBusiness: true
  },
  {
    id: 3,
    type: 'workshop',
    title: 'Live Workshop: Building SaaS with AI',
    author: 'Sarah Chen',
    authorAvatar: 'SC',
    authorRole: 'Senior Product Designer',
    thumbnail: 'https://picsum.photos/seed/saas/800/450',
    date: 'Oct 24, 2024',
    time: '10:00 AM EST',
    category: 'Business',
    publishedAt: '1 day ago',
    isBusiness: false
  },
  {
    id: 4,
    type: 'course',
    title: 'Advanced UI/UX Design Systems',
    author: 'DesignPro Studio',
    authorAvatar: 'DP',
    authorRole: 'Design Agency',
    thumbnail: 'https://picsum.photos/seed/design/800/450',
    duration: '18h 20m',
    rating: 4.8,
    students: 3200,
    price: '$79.99',
    category: 'Design',
    publishedAt: '1 week ago',
    isBusiness: true
  },
  {
    id: 5,
    type: 'college',
    title: 'Stanford Graduate School of Business',
    author: 'Stanford University',
    authorAvatar: 'SU',
    authorRole: 'University',
    thumbnail: 'https://picsum.photos/seed/stanford/800/450',
    location: 'Stanford, CA',
    programs: 12,
    category: 'Education',
    publishedAt: '3 days ago',
    isBusiness: true
  },
  {
    id: 6,
    type: 'program',
    title: 'Executive Leadership Program 2024',
    author: 'Harvard Business School',
    authorAvatar: 'HB',
    authorRole: 'Business School',
    thumbnail: 'https://picsum.photos/seed/harvard/800/450',
    duration: '6 Months',
    certification: 'Professional Certificate',
    category: 'Business',
    publishedAt: '4 days ago',
    isBusiness: true
  },
  {
    id: 7,
    type: 'event',
    title: 'Global Tech Summit: AI & Beyond',
    author: 'TechEvents Global',
    authorAvatar: 'TE',
    authorRole: 'Event Organizer',
    thumbnail: 'https://picsum.photos/seed/summit/800/450',
    date: 'Dec 15, 2024',
    location: 'Virtual / San Francisco',
    category: 'Technology',
    publishedAt: '1 day ago',
    isBusiness: true
  },
  {
    id: 8,
    type: 'live-class',
    title: 'Advanced Python for Data Science',
    author: 'Dr. Michael Brown',
    authorAvatar: 'MB',
    authorRole: 'Data Scientist',
    thumbnail: 'https://picsum.photos/seed/python/800/450',
    time: 'Today, 6:00 PM',
    attendees: 450,
    category: 'Development',
    publishedAt: '2 hours ago',
    isBusiness: false
  },
  {
    id: 9,
    type: 'company',
    title: 'Google Cloud Platform Training',
    author: 'Google Cloud',
    authorAvatar: 'GC',
    authorRole: 'Technology Company',
    thumbnail: 'https://picsum.photos/seed/google/800/450',
    employees: '100k+',
    industry: 'Cloud Computing',
    category: 'Technology',
    publishedAt: '1 week ago',
    isBusiness: true
  },
  {
    id: 10,
    type: 'trainer',
    title: 'Personal Branding Masterclass',
    author: 'Gary Vaynerchuk',
    authorAvatar: 'GV',
    authorRole: 'Serial Entrepreneur',
    thumbnail: 'https://picsum.photos/seed/gary/800/450',
    followers: '10M+',
    category: 'Marketing',
    publishedAt: '5 days ago',
    isBusiness: false
  },
  {
    id: 11,
    type: 'app',
    title: 'SkillBloomer Mobile App',
    author: 'SkillBloomer Tech',
    authorAvatar: 'ST',
    authorRole: 'Software Developer',
    thumbnail: 'https://picsum.photos/seed/app/800/450',
    version: 'v2.4.0',
    downloads: '500k+',
    category: 'Productivity',
    publishedAt: '2 weeks ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 12,
    type: 'webinar',
    title: 'MBA Strategy: Cracking Top B-Schools',
    author: 'Prof. Robert Wilson',
    authorAvatar: 'RW',
    authorRole: 'MBA Admissions Expert',
    thumbnail: 'https://picsum.photos/seed/mba/800/450',
    date: 'Nov 12, 2024',
    time: '7:00 PM IST',
    category: 'Education',
    publishedAt: '1 day ago',
    isBusiness: false
  },
  {
    id: 13,
    type: 'college',
    title: 'London Business School',
    author: 'LBS',
    authorAvatar: 'LB',
    authorRole: 'Business School',
    thumbnail: 'https://picsum.photos/seed/lbs/800/450',
    location: 'London, UK',
    programs: 8,
    category: 'Education',
    publishedAt: '1 week ago',
    isBusiness: true
  },
  {
    id: 14,
    type: 'app',
    title: 'Notion for Students',
    author: 'Notion Labs',
    authorAvatar: 'N',
    authorRole: 'Productivity Tool',
    thumbnail: 'https://picsum.photos/seed/notion/800/450',
    version: 'v3.2',
    downloads: '10M+',
    category: 'Productivity',
    publishedAt: '1 month ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 15,
    type: 'app',
    title: 'Anki Flashcards',
    author: 'Anki Team',
    authorAvatar: 'A',
    authorRole: 'Learning Tool',
    thumbnail: 'https://picsum.photos/seed/anki/800/450',
    version: 'v2.1',
    downloads: '1M+',
    category: 'Productivity',
    publishedAt: '2 months ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 16,
    type: 'app',
    title: 'Coursera Mobile',
    author: 'Coursera Inc.',
    authorAvatar: 'C',
    authorRole: 'Education Platform',
    thumbnail: 'https://picsum.photos/seed/coursera/800/450',
    version: 'v5.4',
    downloads: '50M+',
    category: 'Education',
    publishedAt: '3 weeks ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 17,
    type: 'app',
    title: 'Duolingo',
    author: 'Duolingo',
    authorAvatar: 'D',
    authorRole: 'Language Learning',
    thumbnail: 'https://picsum.photos/seed/duo/800/450',
    version: 'v6.0',
    downloads: '100M+',
    category: 'Education',
    publishedAt: '1 week ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 18,
    type: 'app',
    title: 'Grammarly',
    author: 'Grammarly',
    authorAvatar: 'G',
    authorRole: 'Writing Assistant',
    thumbnail: 'https://picsum.photos/seed/grammarly/800/450',
    version: 'v2.5',
    downloads: '10M+',
    category: 'Productivity',
    publishedAt: '2 weeks ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 19,
    type: 'app',
    title: 'Forest: Stay Focused',
    author: 'Seekrtech',
    authorAvatar: 'F',
    authorRole: 'Focus Tool',
    thumbnail: 'https://picsum.photos/seed/forest/800/450',
    version: 'v4.0',
    downloads: '5M+',
    category: 'Productivity',
    publishedAt: '1 month ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 20,
    type: 'app',
    title: 'WolframAlpha',
    author: 'Wolfram Group',
    authorAvatar: 'W',
    authorRole: 'Knowledge Engine',
    thumbnail: 'https://picsum.photos/seed/wolfram/800/450',
    version: 'v1.4',
    downloads: '2M+',
    category: 'Education',
    publishedAt: '3 months ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 21,
    type: 'app',
    title: 'Khan Academy',
    author: 'Khan Academy',
    authorAvatar: 'K',
    authorRole: 'Non-profit Education',
    thumbnail: 'https://picsum.photos/seed/khan/800/450',
    version: 'v7.2',
    downloads: '10M+',
    category: 'Education',
    publishedAt: '2 weeks ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 22,
    type: 'app',
    title: 'Quizlet',
    author: 'Quizlet Inc.',
    authorAvatar: 'Q',
    authorRole: 'Study Tool',
    thumbnail: 'https://picsum.photos/seed/quizlet/800/450',
    version: 'v8.0',
    downloads: '20M+',
    category: 'Education',
    publishedAt: '1 week ago',
    isBusiness: true,
    url: '#'
  },
  {
    id: 23,
    type: 'podcast',
    title: 'The Future of Web Development',
    author: 'Tech Talk Daily',
    authorAvatar: 'TT',
    authorRole: 'Podcast Host',
    thumbnail: 'https://picsum.photos/seed/podcast1/800/450',
    duration: '45m',
    category: 'Technology',
    publishedAt: '2 days ago',
    isBusiness: false
  },
  {
    id: 24,
    type: 'masters',
    title: 'Master of Science in Artificial Intelligence',
    author: 'Stanford University',
    authorAvatar: 'SU',
    authorRole: 'University',
    thumbnail: 'https://picsum.photos/seed/masters1/800/450',
    duration: '2 Years',
    category: 'Education',
    publishedAt: '1 month ago',
    isBusiness: true
  },
  {
    id: 25,
    type: 'news',
    title: 'New Breakthrough in Quantum Computing',
    author: 'Science Daily',
    authorAvatar: 'SD',
    authorRole: 'News Outlet',
    thumbnail: 'https://picsum.photos/seed/news1/800/450',
    readTime: '5 min read',
    category: 'Technology',
    publishedAt: '3 hours ago',
    isBusiness: true
  },
  {
    id: 26,
    type: 'live-class',
    title: 'Live: Mastering Figma for Beginners',
    author: 'Jane Doe',
    authorAvatar: 'JD',
    authorRole: 'Design Lead',
    thumbnail: 'https://picsum.photos/seed/live1/800/450',
    time: 'Live Now',
    attendees: 1200,
    category: 'Design',
    publishedAt: 'Just now',
    isBusiness: false
  }
];

export const COMMUNITY_GROUPS = [
  {
    id: 1,
    name: 'AI Innovators Hub',
    members: '12.4k',
    description: 'Exploring the frontiers of Generative AI and LLMs.',
    image: 'https://picsum.photos/seed/ai-comm/400/200',
    category: 'AI & Future',
    isPrivate: false
  },
  {
    id: 2,
    name: 'Next.js Masterminds',
    members: '8.2k',
    description: 'Advanced patterns and performance for modern web apps.',
    image: 'https://picsum.photos/seed/next-comm/400/200',
    category: 'Development',
    isPrivate: true
  },
  {
    id: 3,
    name: 'UI/UX Design Collective',
    members: '15.1k',
    description: 'Daily design challenges and critique sessions.',
    image: 'https://picsum.photos/seed/design-comm/400/200',
    category: 'Design',
    isPrivate: false
  },
  {
    id: 4,
    name: 'SaaS Founders Club',
    members: '5.6k',
    description: 'Building and scaling profitable software businesses.',
    image: 'https://picsum.photos/seed/saas-comm/400/200',
    category: 'Business',
    isPrivate: true
  },
  {
    id: 5,
    name: 'Data Science Pioneers',
    members: '9.8k',
    description: 'From statistics to deep learning and neural networks.',
    image: 'https://picsum.photos/seed/data-comm/400/200',
    category: 'Technology',
    isPrivate: false
  },
  {
    id: 6,
    name: 'Digital Marketing Pros',
    members: '11.2k',
    description: 'Mastering growth hacks and performance marketing.',
    image: 'https://picsum.photos/seed/marketing-comm/400/200',
    category: 'Marketing',
    isPrivate: false
  }
];
